# Generated by Django 4.2.2 on 2023-06-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='react',
            old_name='employee_dept',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='react',
            old_name='employee_name',
            new_name='employee',
        ),
    ]
