# Generated by Django 4.2.2 on 2023-06-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_employee_dept_react_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('Case_Number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('State', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Shelter_Home', models.CharField(max_length=300)),
                ('Child_Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('Other', 'Other')], max_length=50)),
                ('DOB', models.DateField()),
                ('Age', models.IntegerField()),
                ('Child_Classification', models.CharField(max_length=200)),
                ('Reason_Admission', models.TextField()),
                ('Reason_Flagging', models.TextField()),
                ('Last_Visit', models.DateField()),
                ('Last_Call', models.DateField()),
                ('Guardian', models.CharField(max_length=50)),
                ('Sibling', models.CharField(max_length=50)),
                ('Shelter_Stay', models.CharField(max_length=100)),
                ('CWC_Last_Review', models.DateField()),
                ('CWC_Last_Order', models.TextField()),
                ('Case_History', models.TextField()),
                ('Newspaper_Date', models.CharField(max_length=100)),
                ('Police_Date', models.CharField(max_length=100)),
                ('Surrender_Date', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='React',
        ),
    ]
