# Generated by Django 4.2.2 on 2023-06-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_case_delete_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Child_Classification',
            field=models.CharField(choices=[('Abandoned', 'Abandoned'), ('Surrendered', 'Surrendered'), ('Orphaned', 'Orphaned'), ('Child Admitted By Family', 'Child Admitted By Family')], max_length=200),
        ),
        migrations.AlterField(
            model_name='case',
            name='Last_Call',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='Last_Visit',
            field=models.CharField(max_length=20),
        ),
    ]
