# Generated by Django 4.2.2 on 2023-06-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_case_action_case_assigned_to_case_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Address', models.TextField()),
                ('Active_Cases', models.IntegerField(default=20)),
                ('Solved_Cases', models.IntegerField(default=30)),
            ],
        ),
    ]
