# Generated by Django 4.2.2 on 2023-06-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_age_social_worker_sw_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='Action_Problem',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='Action_Solution',
            field=models.TextField(null=True),
        ),
    ]
