# Generated by Django 4.2.2 on 2023-06-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_case_action_problem_case_action_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Reason_Flagging',
            field=models.TextField(default=''),
        ),
    ]
