# Generated by Django 4.2.2 on 2023-06-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_case_reason_flagging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='Reason_Flagging',
            field=models.TextField(default='', null=True),
        ),
    ]
