# Generated by Django 4.2.2 on 2023-06-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_case_reason_flagging'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='Newspaper_Doc',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='case',
            name='Police_Doc',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='case',
            name='Progress',
            field=models.CharField(default='Working on Documentaion', max_length=100),
        ),
    ]
